CREATE TABLE ASSIGNMENT (
    ProjectID Int NOT NULL,
    EmployeeNumber Int NOT NULL,
    HoursWorked Int(255) NULL,
    CONSTRAINT ASSIGNMENT_PK PRIMARY KEY (ProjectID, EmployeeNumber),
    CONSTRAINT ASSIGN_PROJ_FK FOREIGN KEY (ProjectID)
    REFERENCES PROJECT (ProjectID)
    ON UPDATE NO ACTION
    On DELETE CASCADE,
    CONSTRAINT ASSIGN_EMP_FK FOREIGN KEY (EmployeeNumber)
    REFERENCES EMPLOYEE (EmployeeNumber)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )
