CREATE TABLE DEPARTMENT (
    DEPARTMENTNAME CHAR(35) NOT NULL,
    BUDGETCODE CHAR(30) NOT NULL,
    OFFICENUMBER CHAR(15) NOT NULL,
    DEPARTMENTPHONE CHAR(12) NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY(DEPARTMENTNAME)
    )
